project_name: rubber_ring
box_name: precise64
box_url: http://files.vagrantup.com/precise64.box
memory: 512
guest_ip: 3.3.3.3

ports:
  - {guest: 3000, host: 3000}

chef_conf:
  databases:
    - sqlite3

  packages:
    - vim

  languages:
    ruby:
      version: 2.0.0-p353
