default: &default
  adapter: postgresql
  username: vagrant
  password: vagrant
  template: template0

development:
  database: rubber_ring_development
  host: localhost
  <<: *default

test:
  database: rubber_ring_test
  host: localhost
  <<: *default

production:
  <<: *default
  host: localhost
  database: rubber_ring_production
